// <auto-generated />
using ECommercial.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommercial.Api.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    partial class ECommerceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommercial.Api.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ECommercial.Api.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ECommercial.Api.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "The device is an entry-level laptop that comes with a powerful AMD Ryzen 7 4700U Mobile Processor along with discrete AMD Radeon graphics options. It allows you to perform tasks with good speed and multitask without any lags, the display is IPS FHD 15.6 inches providing 1920 x 1080 resolution. The laptop is pack with 12 GB RAM .",
                            ImageURL = "/Images/IdeaPed/Ideaped1.png",
                            Name = "Lenovo IdeaPed Slim-3",
                            Price = 484m,
                            Qty = 100
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "HP Laptops starting ₹28149 w/13th Gen Intel Core. Shop Now! Explore affordable range of HP laptops. Built for Multi-tasking & productivity. Shop Now! Save 18% with GST Invoice.",
                            ImageURL = "/Images/IdeaPed/Ideaped2.png",
                            Name = "HP Envy x360",
                            Price = 450m,
                            Qty = 45
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "The HP ProBook 455 Laptop provides growing businesses with the commercial-grade performance",
                            ImageURL = "/Images/IdeaPed/Ideaped3.png",
                            Name = "HP ProBook 455 G9",
                            Price = 480m,
                            Qty = 30
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Powerful Productivity:Intel Core i3-1215U processor delivers unmatched speed and intelligence",
                            ImageURL = "/Images/IdeaPed/Ideaped4.png",
                            Name = "Lenovo IdeaPad Slim 3 AMD 3020e",
                            Price = 400m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "UFC with T-Type HD camera, 1280 x 720 resolution, 720p HD video at 30 fps with Temporal Noise Reduction, Blue glass lens",
                            ImageURL = "/Images/IdeaPed/Ideaped5.png",
                            Name = "Acer Aspire 3",
                            Price = 460m,
                            Qty = 85
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Thin and Laptop (8GB/512GB SSD/Integrated Graphics/Windows 11",
                            ImageURL = "/Images/IdeaPed/Ideaped6.png",
                            Name = "ASUS [SmartChoice] Vivobook 16X ",
                            Price = 590m,
                            Qty = 85
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Included in the box is a USB‑C to Lightning Cable that supports charging and is compatible with USB‑C power adapters and computer ports.",
                            ImageURL = "/Images/IPhone/Iphone1.png",
                            Name = "IPhone 13",
                            Price = 1550m,
                            Qty = 120
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "iPhone 13 Pro. Super Retina XDR display with ProMotion; 6.1‑inch (diagonal) all‑screen OLED display; 2532‑by‑1170-pixel resolution at 460 ppi.",
                            ImageURL = "/Images/IPhone/Iphone2.png",
                            Name = "IPhone 13 pro max",
                            Price = 1600m,
                            Qty = 200
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "upgraded A17 Pro processor, enhanced display, better battery life and improved camera system",
                            ImageURL = "/Images/IPhone/Iphone3.png",
                            Name = "IPhone 15 Pro Max",
                            Price = 1400m,
                            Qty = 300
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Tipped to Launch in 2022: OnePlus 10 Pro, Nord 2 Lite, Nord 2T, and More - MySmartPrice",
                            ImageURL = "/Images/IPhone/Iphone4.png",
                            Name = "OnePlus Mobiles",
                            Price = 1200m,
                            Qty = 20
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "reliable choice for everyday tasks and demanding apps. When compared to the iPhone 11 and iPhone 12",
                            ImageURL = "/Images/IPhone/Iphone5.png",
                            Name = "Apple iPhone 13",
                            Price = 1100m,
                            Qty = 15
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "Comfortable Golden Bracelet in most sizes",
                            ImageURL = "/Images/Shoes/Bracelet.png",
                            Name = "Golden Bracelet",
                            Price = 100m,
                            Qty = 50
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Description = "On-ear Golden Headphones - these headphones are not wireless",
                            ImageURL = "/Images/Shoes/HeadPhone1.png",
                            Name = "On-ear Golden Headphones",
                            Price = 150m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Description = "On-ear Black Headphones - these headphones are not wireless",
                            ImageURL = "/Images/Shoes/HeadPhone2.png",
                            Name = "On-ear White Headphones",
                            Price = 200m,
                            Qty = 70
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Description = "Colorful attractive watch - available in most sizes",
                            ImageURL = "/Images/Shoes/Watch1.png",
                            Name = "Colorful Watch",
                            Price = 120m,
                            Qty = 120
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Description = "Colourful Watch - available in most sizes and colurs.",
                            ImageURL = "/Images/Shoes/Watch2.png",
                            Name = "SkyBlue Colourful Watch",
                            Price = 200m,
                            Qty = 100
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            Description = "Birkenstock Watch - available in single colour",
                            ImageURL = "/Images/Shoes/Watch3.png",
                            Name = "Oldest Watches",
                            Price = 105m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Description = "White and blue Porcelain Table Lamp",
                            ImageURL = "/Images/Electronic/Furniture1.png",
                            Name = "Porcelain Table Lamp",
                            Price = 15m,
                            Qty = 100
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "Office Table Lamp",
                            ImageURL = "/Images/Electronic/Furniture2.png",
                            Name = "Office Table Lamp",
                            Price = 20m,
                            Qty = 73
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Description = "Very comfortable gaming setup with all features",
                            ImageURL = "/Images/Electronic/Gaming1.png",
                            Name = "Gaming Setup",
                            Price = 150m,
                            Qty = 90
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Description = "Very comfortable keyboard with low coast.",
                            ImageURL = "/Images/Electronic/KeyBoard.png",
                            Name = " Black-Gray KeyBoard",
                            Price = 120m,
                            Qty = 95
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Description = "White, Red and another different colours comfortable keyboard.",
                            ImageURL = "/Images/Electronic/KeyBoard1.png",
                            Name = "New Coloured KeyBoard",
                            Price = 15m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Description = "New product for daily use.",
                            ImageURL = "/Images/Electronic/Mouse.png",
                            Name = "Mouse",
                            Price = 40m,
                            Qty = 73
                        });
                });

            modelBuilder.Entity("ECommercial.Api.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconCSS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconCSS = "fas fa-spa",
                            Name = "Ideaped"
                        },
                        new
                        {
                            Id = 2,
                            IconCSS = "fas fa-couch",
                            Name = "IPhone"
                        },
                        new
                        {
                            Id = 3,
                            IconCSS = "fas fa-headphones",
                            Name = "Mens"
                        },
                        new
                        {
                            Id = 4,
                            IconCSS = "fas fa-shoe-prints",
                            Name = "QElectronics"
                        });
                });

            modelBuilder.Entity("ECommercial.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserName = "Manoj"
                        },
                        new
                        {
                            Id = 2,
                            UserName = "Suraj"
                        });
                });

            modelBuilder.Entity("ECommercial.Models.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyCertificateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("ECommercial.Models.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("ECommercial.Api.Entities.Product", b =>
                {
                    b.HasOne("ECommercial.Api.Entities.ProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
